import { test } from "node:test";
import assert from "node:assert/strict";

import { register } from "../lib/clean-ai-review-comments.js";
import { makeApp, makeOctokit, makeContext } from "./helpers/mock-github.js";

// ---------------------------------------------------------------------------
// issue_comment.created / .edited  (Augment PR Summary lives here)
// ---------------------------------------------------------------------------

test("issue_comment: a changed Copilot overview is patched via updateComment", async () => {
  const { app, dispatch } = makeApp();
  register(app);
  const octokit = makeOctokit();
  const body =
    "Intro.\n## Pull request overview\nLine one.\nLine two.\nLine three.";
  const context = makeContext({
    octokit,
    payload: {
      issue: { pull_request: {} },
      comment: { id: 99, body, user: { login: "Copilot" } },
    },
  });
  await dispatch("issue_comment.created", context);

  const patches = octokit.calls.filter(
    (c) => c.method === "rest.issues.updateComment"
  );
  assert.equal(patches.length, 1);
  assert.equal(patches[0].args.comment_id, 99);
  assert.ok(patches[0].args.body.includes("<details>"));
});

test("issue_comment: an unchanged body is NOT patched", async () => {
  const { app, dispatch } = makeApp();
  register(app);
  const octokit = makeOctokit();
  const context = makeContext({
    octokit,
    payload: {
      issue: { pull_request: {} },
      comment: {
        id: 99,
        body: "Just a plain human comment.",
        user: { login: "david", type: "User" },
      },
    },
  });
  await dispatch("issue_comment.created", context);
  assert.equal(octokit.calls.length, 0);
});

test("issue_comment: comments not on a PR are ignored", async () => {
  const { app, dispatch } = makeApp();
  register(app);
  const octokit = makeOctokit();
  const context = makeContext({
    octokit,
    payload: {
      issue: {}, // no pull_request
      comment: {
        id: 99,
        body: "Intro.\n## Pull request overview\na\nb\nc",
        user: { login: "Copilot" },
      },
    },
  });
  await dispatch("issue_comment.created", context);
  assert.equal(octokit.calls.length, 0);
});

// ---------------------------------------------------------------------------
// pull_request_review_comment.created / .edited (inline suggestions)
// ---------------------------------------------------------------------------

test("review_comment: an Augment 'Fix This' link is stripped via updateReviewComment", async () => {
  const { app, dispatch } = makeApp();
  register(app);
  const octokit = makeOctokit();
  const body =
    "Problem here.\n\n[![Fix This](https://public.augment-assets.com/x.png)](https://augmentcode.com/fix?id=1)";
  const context = makeContext({
    octokit,
    payload: {
      pull_request: { number: 4 },
      comment: { id: 55, body, user: { login: "augmentcode[bot]" } },
    },
  });
  await dispatch("pull_request_review_comment.created", context);

  const patches = octokit.calls.filter(
    (c) => c.method === "rest.pulls.updateReviewComment"
  );
  assert.equal(patches.length, 1);
  assert.equal(patches[0].args.comment_id, 55);
  assert.ok(!patches[0].args.body.includes("augmentcode.com"));
});

test("review_comment: a plain comment is left alone", async () => {
  const { app, dispatch } = makeApp();
  register(app);
  const octokit = makeOctokit();
  const context = makeContext({
    octokit,
    payload: {
      pull_request: { number: 4 },
      comment: { id: 55, body: "nit: rename this", user: { login: "david" } },
    },
  });
  await dispatch("pull_request_review_comment.created", context);
  assert.equal(octokit.calls.length, 0);
});

// ---------------------------------------------------------------------------
// pull_request_review.submitted / .edited (review summaries)
// ---------------------------------------------------------------------------

test("review.submitted: a LinearB summary is collapsed via updateReview", async () => {
  const { app, dispatch } = makeApp();
  register(app);
  const octokit = makeOctokit();
  const body =
    "Intro.\n### ✨ PR Review\nFound issues:\n<details><summary>Issue 1</summary>x</details>\nGenerated by LinearB AI and added by gitStream";
  const context = makeContext({
    octokit,
    payload: {
      pull_request: { number: 8 },
      review: { id: 21, body, user: { login: "gitstream-cm[bot]", type: "Bot" } },
    },
  });
  await dispatch("pull_request_review.submitted", context);

  const patches = octokit.calls.filter(
    (c) => c.method === "rest.pulls.updateReview"
  );
  assert.equal(patches.length, 1);
  assert.equal(patches[0].args.review_id, 21);
  assert.ok(patches[0].args.body.includes("LinearB PR Summary"));
});
