# Deploys as a free tier Web Service in Render
# https://dashboard.render.com/
version: "1"
projects:
- name: github-bot-ai-reviewed-prs
  environments:
  - name: Production
    services:
    - type: web
      name: github-bot-ai-reviewed-prs
      runtime: node
      repo: https://github.com/HealthengineAU/github-bot-ai-reviewed-prs
      plan: free
      envVars:
      - key: PRIVATE_KEY
        sync: false
      - key: WEBHOOK_SECRET
        sync: false
      - key: APP_ID
        sync: false
      region: ohio
      buildCommand: npm install
      startCommand: npm run start
      autoDeployTrigger: commit
