apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "ghbot.name" . }}
    chart: {{ template "ghbot.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "ghbot.fullname" . }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secrets }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
