env:
  ECR_REPO_URL: 759931498410.dkr.ecr.ap-southeast-2.amazonaws.com/github-bot-ai-reviewed-prs-prod
  IMAGE_TAG: $BRANCH_SLUG

steps:
  # Run the scan.sh script that's installed on our Buildkite deployment agents.
  # The $GITHUB_PR_TOKEN env var is in the Buildkite secrets bucket.
  - label: ':mag: Vulnerability Scanning'
    agents:
      queue: prod1
    command: scan.sh
    retry:
      manual:
        permit_on_passed: true
