apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app: {{ template "ghbot.name" . }}
    chart: {{ template "ghbot.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "ghbot.fullname" . }}
spec:
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
  selector:
    app: {{ template "ghbot.name" . }}
    release: {{ .Release.Name }}
  type: {{ .Values.service.type }}
